//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karellen.Negocio.Mensagem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karellen.Negocio.Mensagem.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou senha inválido.
        /// </summary>
        public static string MN005 {
            get {
                return ResourceManager.GetString("MN005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string MN010 {
            get {
                return ResourceManager.GetString("MN010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Identity não corresponde a nenhum usuário.
        /// </summary>
        public static string MN011 {
            get {
                return ResourceManager.GetString("MN011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não são iguais.
        /// </summary>
        public static string MN012 {
            get {
                return ResourceManager.GetString("MN012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta criada com sucesso.
        /// </summary>
        public static string MN013 {
            get {
                return ResourceManager.GetString("MN013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de conta - Karellen.
        /// </summary>
        public static string MN015 {
            get {
                return ResourceManager.GetString("MN015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por criar uma conta no Karellen. Para acessar, acesse o link abaixo.
        /// </summary>
        public static string MN016 {
            get {
                return ResourceManager.GetString("MN016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um problema ao pegar suas credenciais. Por favor,crie uma conta local e adicione  seu login social.
        /// </summary>
        public static string MN017 {
            get {
                return ResourceManager.GetString("MN017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma conta com este email. Por favor, entre com sua conta usando este email e/ou adicione o login social.
        /// </summary>
        public static string MN018 {
            get {
                return ResourceManager.GetString("MN018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do título é de 30 caracteres.
        /// </summary>
        public static string MN019 {
            get {
                return ResourceManager.GetString("MN019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorrência criada com sucesso.
        /// </summary>
        public static string MN020 {
            get {
                return ResourceManager.GetString("MN020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações atualizadas com sucesso.
        /// </summary>
        public static string MN021 {
            get {
                return ResourceManager.GetString("MN021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão de acesso a esta página. Por favor, entre com uma conta com acesso..
        /// </summary>
        public static string MN022 {
            get {
                return ResourceManager.GetString("MN022", resourceCulture);
            }
        }
    }
}
